language: csharp
solution: Basic.Azure.Storage.sln
install:
  - nuget restore Basic.Azure.Storage.sln
  - nuget install NUnit -Pre -OutputDirectory testrunner
  - nuget install NUnit.Console -Pre -OutputDirectory testrunner
script:
#  - xbuild /p:Configuration=Release Basic.Azure.Storage.sln
  - ls ./testrunner
#  - mono ./testrunner/NUnit.Console/tools/nunit-console.exe ./Basic.Azure.Storage.Tests/bin/Release/Basic.Azure.Storage.Tests.dll
